### ISSUE TITLE
Re-enable certain SharedClassesAPI tests on windows?

### ISSUE THREAD

**Issue by cjjdespres** [adoptium/openj9-systemtest#157]
I happened to be going through some of the test code and noticed this:

https://github.com/adoptium/openj9-systemtest/blob/ce686f5d4aee846ce948b039beb3c264a9bb5c7b/openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java#L212-L214

but the end of the thread in https://github.com/eclipse-openj9/openj9-systemtest/issues/38 says that it was resolved. Maybe the tests should be re-enabled?

**Comment by llxia** [comment]
@LongyuZhang could try to revert https://github.com/adoptium/openj9-systemtest/pull/40/ and see if you can run the test.
According to https://github.com/adoptium/openj9-systemtest/blob/ce686f5d4aee846ce948b039beb3c264a9bb5c7b/openj9.test.sharedClasses.jvmti/docs/README.md?plain=1, the corresponding test should be `SharedClassesAPI`

**Comment by LongyuZhang** [comment]
Sure, I will try the revert and run to see if it can pass.

**Comment by LongyuZhang** [comment]
Noticed this test `SharedClassesAPI` has been failing on the xlinux weekly test already (https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.system_x86-64_linux_testList_1/221/tapTestReport/):
```
STF 21:38:25.321 - Monitoring processes: JVMT
 JVMT stderr JVMJ9TI001E Agent library /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_testList_1/jvmtest/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/linux/libsharedClasses.so could not be opened (/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_testList_1/jvmtest/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/linux/liblibsharedClasses.so.so: cannot open shared object file: No such file or directory)
 JVMT stderr JVMJ9VM015W Initialization error for library j9jvmti29(-3): JVMJ9VM009E J9VMDllMain failed
 STF 21:38:25.358 - **FAILED** Process JVMT ended with exit code (1) and not the expected exit code/s (0)
 STF 21:38:25.358 - Monitoring Report Summary:
 STF 21:38:25.358 -   o Process JVMT ended with exit code (1) and not the expected exit code/s (0)
 STF 21:38:25.359 - Killing processes: JVMT
 STF 21:38:25.359 -   o Process JVMT pid 7166 is not running
 **FAILED** at step 65 (DefaultLocGrpAccessJVMTI - Check Shared Classes Caches). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_testList_1/aqa-tests/TKG/../TKG/output_17274936404586/SharedClassesAPI_0/20240927-213705-SharedClassesAPI/execute.pl line 2213.
 STF 21:38:25.653 - **FAILED** execute script failed. Expected return value=0 Actual=1
```
Should we open an issue for this failure first?

**Comment by pshipton** [comment]
There is already and issue and a fix that will probably be merged tomorrow.
https://github.com/eclipse-openj9/openj9/issues/20194
